# Generated by Django 2.1.4 on 2019-09-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=20)),
                ('grade_crate_data', models.DateTimeField()),
                ('grade_gril_num', models.IntegerField()),
                ('grade_boy_num', models.IntegerField()),
                ('grade_isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('student_gender', models.BooleanField(default=True)),
                ('student_age', models.IntegerField()),
                ('student_contend', models.CharField(max_length=20)),
                ('student_isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
