# Generated by Django 2.1.4 on 2019-09-14 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_grade1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app1.Grades'),
        ),
    ]
